name: Android

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linux_test:
    name: Test Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install swiftly
        run: curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash -s -- -y
      - name: Install the latest Swift toolchain
        run: swiftly install 6.0.2
      - name: Install the Android SDK
        run: swift sdk install https://github.com/finagolfin/swift-android-sdk/releases/download/6.0.2/swift-6.0.2-RELEASE-android-24-0.1.artifactbundle.tar.gz --checksum d75615eac3e614131133c7cc2076b0b8fb4327d89dce802c25cd53e75e1881f4
      - name: Build
        run: swift build --build-tests --swift-sdk aarch64-unknown-linux-android24
